### ISSUE TITLE
Extract all links from a webpage

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#110]
Using [`reqwest`](https://crates.io/crates/reqwest) to fetch the page + [`html5ever`](https://crates.io/crates/html5ever) to extract links.

**Comment by luisbg** [comment]
This one looks fun. I can work on it if you'd like :smile:

**Comment by henninglive** [comment]
Should the example use [html5ever ](https://crates.io/crates/html5ever)directly or can it use [select](https://crates.io/crates/select), which wraps the html5ever API with a much more user friendly API?

**Comment by luisbg** [comment]
The API of select does look a lot nicer and easier to use.
https://github.com/utkarshkukreti/select.rs/blob/master/examples/stackoverflow.rs

It all depends on if this cookbook wants to use the key crates directly, or nice wrappers like this are valid.

What do you think @brson and @dtolnay ?

**Comment by dtolnay** [comment]
Great question. Thanks for bringing this up.

I would prefer to leave this up to @brson because I know they had some strong opinions about crate selection that haven't been written down yet https://github.com/brson/rust-cookbook/issues/64#issuecomment-300650595. They are on vacation this week though so let's put this example on hold until Monday. Sorry about that @luisbg, would you pick a different issue for now?

**Comment by luisbg** [comment]
No problem. I will wait a pick a different one for now.

**Comment by brson** [comment]
@luisbg let's go ahead and do this, and use whichever crate you like.

Neither html5ever or select were on my radar for this project, but they accomplish a useful task, and I mostly want to say 'yes' and keep things moving. Let's do try to avoid expanding the scope too greatly though. I think a good guideline here is that using html5ever/select is in support of reqwest use cases, so that's ok.

**Comment by luisbg** [comment]
@brson great!

I am traveling this week for some work meetings but as soon as I can I will look into this and submit some code. Thanks :smile:

**Comment by sebasmagri** [comment]
@luisbg @brson could we use this to replace the [Web Scraper RustBridge Tutorial](https://community.rs/rustbridge/web-scraper/README.html)?

**Comment by sb89** [comment]
I came up with the following for this:

```
extern crate reqwest;
#[macro_use]
extern crate error_chain;
extern crate select;

use std::io::Read;
use select::document::Document;
use select::predicate::Name;

error_chain! {
    foreign_links {
        ReqError(reqwest::Error);
        IoError(std::io::Error);
    }
}

fn run() -> Result<()> {
    let mut res = reqwest::get("https://www.rust-lang.org/en-US/")?;

    let mut buffer = String::new();
    res.read_to_string(&mut buffer)?;

    let html: &str = &buffer;

    let document = Document::from(html);

    for node in document.find(Name("a")){
        if let Some(link) = node.attr("href") {
            println!("{}", link);
        }
    }

    Ok(())
}

quick_main!(run);
```

I'm still learning Rust myself so any criticism is welcome.

**Comment by luisbg** [comment]
@sb89 I know you are new to Rust and maybe to Open Source communities. It is customary to ask the person assigned to the issue if they have done any progress before working on or submitting a patch.

The reason for this is to avoid stepping in each other's toes. Which you've done in this case, since I had spent some time on this but wasn't ready to post yet. You used reqwest and select like I planned to. The first to get the page, the second to get the anchors. Looks like you render my work useless. Letting you know since I understand making this mistake when starting to contribute to Open Source.

I haven't tested your code. I can read it tomorrow. So far it looks good.

Thanks for your contribution. I appreciate the time spent on this, and welcome to Rust.

**Comment by luisbg** [comment]
@sb89 looks good to me. Two things to do.

First one is to submit this as a Pull Request, if you don't know how to do it I can help with that.

Second is removing the error_chain dependency. Just look at how the other examples in the cookbook are written, using:
 fn run() -> Result<()> { .. }
but not quick_main(). This is good for brevity.

Thanks for your code :smile:

**Comment by sb89** [comment]
@luibs Thanks. I should have checked whether this was still being worked on before I submitted my solution, my apologies.

**Comment by luisbg** [comment]
@sb89, no problem. Have it mind for future contributions. Welcome to Rust
