### ISSUE TITLE
Add "Recursively calculate file sizes at given depth" recipe

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#179]
Use walkdir's min_dir/max_dir to calculate the total file sizes at some depth of the filesystem tree.

**Comment by crypto-universe** [comment]
Hi, @brson ! I can do that!

**Comment by crypto-universe** [comment]
@brson , check, please, if the code is good enough to be published in the book :)

**Comment by luser** [comment]
One nit: we should tweak this example to use `f.file_type().is_file()` instead of requiring the metadata to filter out non-files. It seems minor, but the `WalkDir` iterator gets the `file_type()` data for free during iteration (since it's stored in the directory entries), whereas calling `metadata()` generally means an additional call to `stat` each item. Those extra syscalls can add up, so it's better to filter on the already-available data first.

Here's an example I wrote when I was learning to use the walkdir API:
https://gist.github.com/luser/e1aee2b269551bb181172a55448c8787

**Comment by budziq** [comment]
@luser fair point, calling `file_type()` would be a reasonable performance optimization and your implementation is also very nice. 

If you are willing to provide/change this or any other example with textual description, you are very welcome to open a PR :)

For now I'm closing this issue with https://github.com/brson/rust-cookbook/issues/181
