### ISSUE TITLE
"Decompress a tarball while removing a prefix from the paths" recipe

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#187]
The purpose of this recipe is to show iteration over the entries in the tarball, not just use Archive::unpack.

**Comment by j-haj** [comment]
I have a working example for this, but would like to get some clarification to the "... while removing a prefix ..." part. Suppose the tarball has the structure:

```
test/
|_ A.txt
|_ B.txt
```
are you looking for there to be additional logic to remove "test/" (for example) from the paths of A.txt and B.txt?

**Comment by budziq** [comment]
Hi @j-haj 

> I have a working example for this, 

Then PR away :smile: 

> but would like to get some clarification to the "... while removing a prefix ..." part.

This example is aimed mostly to showcase iteration and per entry manipulation instead of a single blanket ` Archive::unpack` over the whole archive.

Suppose you have a tarball with similar structure (or with several dirs at root level like `backups`):
```
backups/
└── log/
    ├── dmesg
    ├── nginx/
    │   ├── access.log
    │   ├── access.log.1
    │   ├── error.log
    │   └── error.log.1
    ├── syslog
    └── syslog.1
```

And you would like to have it extracted to something like:
```
log/
├── dmesg
├── nginx/
│   ├── access.log
│   ├── access.log.1
│   ├── error.log
│   └── error.log.1
├── syslog
└── syslog.1

```
or even

```
logs_2017-06-19/
├── access.log
├── access.log.1
├── dmesg
├── error.log
├── error.log.1
├── syslog
└── syslog.1
```

Whatever feels the most realistic and useful to you gets the job done.

**Comment by j-haj** [comment]
Perfect that was my initial interpretation so things are on the right track. One follow-up question: since these should be self contained, I have a small section that creates the tarball first (following the methodology of a prior recipe), and then I iterate through that. Is there any opposition to that? This prevents us from having a comment along the lines of "First, find a tarball we can use... then change this string to match the path to your tarball... etc.".

I want to clean up the surrounding parts of the example and then will submit a PR.

**Comment by budziq** [comment]
I would suggest mimicking the ["Decompress a tarball"](https://brson.github.io/rust-cookbook/app.html#ex-tar-decompress). Hardcode the path and make the example `no_run`.

**Comment by j-haj** [comment]
Well it seems I've run into some issues when testing on more complex directory structures so my PR will be a little delayed while I dig into this.

**Comment by budziq** [comment]
> Well it seems I've run into some issues when testing on more complex directory structures

It sounds that you are trying to do more than required from this example :smile: I would suggest pushing a PR early in order not to waste time.

**Comment by j-haj** [comment]
I had introduced a bug in my code that was causing the issue -- whoops! I am just trying to sort out handling the errors properly then I should have a PR.

**Comment by j-haj** [comment]
See #199 for PR

**Comment by budziq** [comment]
@j-haj you can already see your [example deployed](https://brson.github.io/rust-cookbook/app.html#ex-tar-strip-prefix) keep'em coming :smile:!

**Comment by j-haj** [comment]
@budziq thanks for all the guidance!! I'll definitely be working on more
