### ISSUE TITLE
Add "Make a HTTP GET request after parsing a URL" example for url/reqwest crates

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#39]
Hard part here will be figuring out what to do about running the examples in the test suite without actually hitting the network.

**Comment by budziq** [comment]
I guess that the best option would be to use skeptic's `rust,no_run` annotation which would still require examples to compile without actual execution.

Otherwise we would need to spin some minimal webserver locally which would not be ideal. The problem will return on nearly all nontrivial examples like database interaction, process management, fs manipulation, etc. (FFI?).

I seam to be spamming every single thread. Sorry for that.

**Comment by budziq** [comment]
The https://github.com/brson/rust-cookbook/pull/53 should resolve this issue once reqwest catches up with the newest serde seanmonstar/reqwest#79
