### ISSUE TITLE
incorrect formatting of raw strings

### ISSUE THREAD

**Issue by fbstj** [brson/rust-cookbook#58]
the code formatting for many of the snippets 'breaks' when it sees quote-pairs inside raw strings `r#"like "this" eg"#`, it would unhighlight the word 'this'. probably because it's not highlighting the raw stirng just the `""` pairs between the `##` 's

I know this is probably not a bug with /this/ repository but I wouldn't know where to look to actually fix it

**Comment by brson** [comment]
Thanks for the report. I guess this is in mdbook or commonmark cc @azerupi

**Comment by azerupi** [comment]
Syntax highlighting is handled by [highlight.js](https://highlightjs.org/). It could be that it is already fixed upstream but that we are just not up-to-date. If this bug is still present in the latest version I guess it should be fixed there first.

Anyways, I added a tracking issue on the mdBook repo :)

**Comment by dtolnay** [comment]
This is being tracked in https://github.com/azerupi/mdBook/issues/269.
